export const FETCH_ADVANTAGES_REQUEST = 'FETCH_ADVANTAGES_REQUEST';
export const FETCH_ADVANTAGES_SUCCESS = 'FETCH_ADVANTAGES_SUCCESS';
export const FETCH_ADVANTAGES_FAILURE = 'FETCH_ADVANTAGES_FAILURE';
export const FETCH_MENU_REQUEST = 'FETCH_MENU_REQUEST';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAILURE = 'FETCH_MENU_FAILURE';
